### ISSUE TITLE
Please add an example for hapi.

### ISSUE THREAD

**Issue by kuronekomichael** [dthree/vantage#25]
Please add an example for [hapi](http://hapijs.com/).
I know that both express.js and koa.js are good, but I just prefer [hapi](http://hapijs.com/)! :heart:

**Comment by dthree** [comment]
Sure! I haven't officially supported hapi (probably simply because I'm not familiar with it), but let me do a little research - supporting it should be simple.

If anyone else out there is pretty familiar with hapi, I'd love your help to get this working. The logic for parsing the web server middleware being passed in is in `./lib/server.js` - `init` function.

**Comment by dthree** [comment]
@kuronekomichael  Okay - Vantage now supports Hapi!

There's an example in the examples folder, and the readme has an implementation example as well.

**Comment by kuronekomichael** [comment]
@dthree Thank you so, so much! I’m impressed! :heart_eyes:

**Comment by dthree** [comment]
@kuronekomichael glad I could help :)
