### ISSUE TITLE
Maximum of 2 arguments?

### ISSUE THREAD

**Issue by slezica** [dthree/vantage#28]
I've just spent an hour trying to figure out why the 3rd argument of my command was not reaching the action function.

Eventually found this line:

    vantage.j:787    var supportedArgs = 2;

Changed it, and voilá.

Is there a reason for this? The `Command` custructor will happily take more arguments, and the `help` command **lists them, even though they are ignored**. 

It's limiting and very confusing

**Comment by dthree** [comment]
Haha -  I had just put that in yesterday, as yesterday I just put in supported for variadic arguments:

    .command('foo [arg] [variadicArgs...]'

Before this, only one command was supported. You can technically do unlimited commands with variadic args. In the above, if you did this:

```bash
$ foo bar lorem ipsum
```
It would expose itself like this:

```js
args:
{
  arg: 'bar',
  variadicArgs: ['lorem', 'ipsum']
}
```

With variadic args, every subsequent arg gets filed in as another item in an array.

I implemented this functionality because this duplicates what commander.js does, and that is what my command syntax is trying to replicate.

However, I can technically increase it, you are right. I guess I might as well.

**Comment by slezica** [comment]
I understand. The variadic mechanic is definitely more powerful, but takes away the `help` automatic parameter list.

I can also see that having many arguments would make `help` look awful and introduce functions with an unruly amount of parameters in the code side.

Perhaps you could increase the limit to `5`, and throw an error when a `Command` is defined with more arguments than that. I reckon the confusion is the real problem (you define `n` params, get only `2`).

Thanks for the quick response :) I really like `vantage`, and I'm enthusiastic about seeing it under such active development.

**Comment by dthree** [comment]
Thanks for the response and I agree.

Since you're not the first that's brought this up, I went and fixed this, so it does accept up to 10 args, as well as variadic args (variadic should be last, as it eats up everything after it).

I'll emphasize variadic args as a best practice in the docs, and that should be fine.

So you're all good to go! :rocket:

And thanks! Glad you like Vantage!
