### ISSUE TITLE
Unnecessary dependency: npm

### ISSUE THREAD

**Issue by Downchuck** [dthree/vantage#34]
It seems to me that having "npm" in the package as a dependency is not needed, and adds about 20Megs to the node_modules folder.

**Comment by dthree** [comment]
Thanks and I agree. I am about to do a large split of Vantage in to two versions: `vantage` proper will be a framework for building interactive CLIs, and the `use` function as well as the `client` / `server` functionality will be removed.

`vantage-io` will extend vantage to what it is currently, adding the cilent / server functionality. I'm probably going to make `vantage-use` a module that imorts the `use` function, which is why `npm` is a dependency. So this should be fixed in about a week or less.

**Comment by Downchuck** [comment]
That sounds like a good plan, looking forward to the update.

**Comment by dthree** [comment]
I'm happy :)

Might be sooner than we think. Started today. `vantage` proper is going to be as slim as possible as I'll be positioning it as a framework in its own right and so expect it to be dependency for a ton of app, as new breed of interactive CLI apps, like this one:

https://github.com/dthree/wat

I'll let you know when it's done.

**Comment by dthree** [comment]
@Downchuck Okay did the mondo refactor.

[Vorpal.js](https://github.com/dthree/vorpal) is all of Vantage's CLI functionality extracted as its own framework.

[Vantage.js](https://github.com/dthree/vantage) depends on and *extends* Vorpal, inheriting all of its properties. It adds the client, server, firewall and authentication functionality to Vorpal.

The `use` function (along with the `npm` module) was extracted out of Vantage as well and is now [vorpal-use](https://github.com/vorpaljs/vorpal-use). This extension can be imported into either Vantge or Vorpal.

Vorpal is 1/4th the size of Vantage. If you just want the CLI framework, use Vorpal. If you want Vorpal with wings, use Vantage.
