### ISSUE TITLE
Best way to asynchronously logs to Vantage?

### ISSUE THREAD

**Issue by MrHalfman** [dthree/vantage#35]
Hi,

I wanted to make a debug as we can see in the Gif.
So, using express, I started by making a middleware to get all requests information but now I'm asking myself on how to properly send theses logs to my vantage instance.

I thought that I can send the log function of my debug command to the global scope (then the middleware can use it to log everything he has to) but I find this very crappy.

Thanks for your councils.

**Comment by dthree** [comment]
I think the cleanest way to do this is to simply have a flag on whatever logging middleware you have. Suppose all of your logging goes through a function the parses it, logs it to a file and then might log it to the console as well. That logging function can have an internal flag of true or false in regards logging to the console.

It's good to keep vantage commands in their own file. Because of the separation of concerns, perhaps your logging object can expose a public function to enable or disable console logging. You then simply need to pass an instance of your logging object into the vantage file and have vantage call that public function, which will toggle the logging flag.

Something like (super simplified):

```js

function setupVantage(logger) {
  vantage
    .command('debug <domain>')
    .action(function(args, cb){
      var domain = args.domain;
      domain = (domain === 'off') ? void 0 : domain;
      logger.log(domain);
    });
}
```

This `logger.log` would trigger the logger's own internal flag, which would be checked whenever something elsewhere in your app is logged.

Does that sound a little better?

**Comment by MrHalfman** [comment]
Thanks for your answer.

Yep it's better but does this solution will properly output logs?

I mean that I thought the usage of ```this.log(str)``` in the action's callback was the only way to ensure that the logs are sent to the connected client and the local terminal.

**Comment by dthree** [comment]
Haha you are correct. You should separetely (wherever you see cleanest) be able to pass in the logging object to your logger.

    logger.use(vantage);

```js
Logger.prototype.use = function(obj) {
  this.console = obj;
}

Logger.prototype.log = function(str) {
  this.console.log(str);
}
```

**Comment by dthree** [comment]
Closing this. Feel free to ask if you have more questions.

**Comment by MrHalfman** [comment]
Yep, thanks for your answers. I will try your solution.

**Comment by dthree** [comment]
ok great.

**Comment by dthree** [comment]
btw, just did a major refactor on Vantage, so it now depends on Vorpal. The readme goes over it, but you should probably check it out (doesn't necessarily affect you, but it can)

**Comment by MrHalfman** [comment]
Oh, okay. I will take a look on it.
